const randomnumber = Math.trunc(Math.random() * 50) + 1;
let score = 5
let highscore = 0
console.log(randomnumber)
const x = [
    {
        message: score, 
        id: "#scoreValue",
        data: "more"
    },
    {
        message: "😒😒😒 Too High, Enter Lower",
        id: ".message",
        data: "more"
    },
    {
        message: score, 
        id: "#scoreValue",
        data: "less"
    },
    {
        message: "😢😢😢Too Low, Enter Higher",
        id: ".message",
        data: "less"
    }
]
// create initial value for score, highscore and randdom number generated by compiter

const displayMessage = function(message, id){
    document.querySelector(id).textContent = message;
}
displayMessage(score, "#scoreValue")
//when the button check is clicked create a event handler and a function to be triggered
document.getElementById("checkButton").addEventListener("click", () => {
	//get input
	const user_guess = parseInt(document.getElementById("userGuess").value);
	//if no input 
	if(isNaN(user_guess)){
		displayMessage("please enter a number", ".message")
        return
     } else if(user_guess == randomnumber){
        if(score > highscore){
            highscore = score
            displayMessage(score, "#scoreValue1")
        }
        displayMessage(randomnumber, "#number")
        displayMessage("😂😊🤣 Hurray, ", ".message")
        document.querySelector(".game-container").style.backgroundColor = "#ff4b13"
        return
    } 
    if (score < 1){
        displayMessage("😒😒😒 Looser", ".message")
        return
    } else {
        score --
    }
    

    x.map(data => {
        (data.data === "less" && user_guess < randomnumber) ?
            displayMessage(data.message, data.id)
        : (data.data === "more" && user_guess > randomnumber) ?
            displayMessage(data.message, data.id)
        : ""
        })
        document.querySelector(".game-container").style.backgroundColor = "#6ec6ff"
        displayMessage(score, "#scoreValue")
    })

document.getElementById("retryButton").addEventListener("click", function(){
    score = 5
    displayMessage(score, "#scoreValue")
    document.querySelector(".game-container").style.backgroundColor = "#6ec6ff"
    displayMessage("", ".message")
    document.querySelector("#userGuess").value = ""
    document.querySelector("#number").innerHTML = "Unknown"
})
